services:
  es8:
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:8.17.2
    container_name: es8
    environment:
      - node.name=es8
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kib8:
    image: docker.elastic.co/kibana/kibana:8.17.2 # Use Kibana image instead of Elasticsearch
    container_name: kib8
    environment:
      - ELASTICSEARCH_HOSTS=http://es8:9200 # Corrected variable name
    ports:
      - 5601:5601
    networks:
      - elastic
    depends_on:
      - es8

volumes:
  data:
    driver: local

networks:
  elastic:
    driver: bridge
